from opentrons import protocol_api,types
import serial
import time
import sys


metadata = {'apiLevel': '2.3'}

def run(protocol: protocol_api.ProtocolContext):

    if protocol.is_simulating() == False:
        sys.path.insert(0, "/data")
        import DispenseUnit_1161
        import pyTMCL
        serial_port = serial.Serial("/dev/ttyACM0", 9600)
        bus = pyTMCL.connect(serial_port)
        pump_1 = DispenseUnit_1161.DispenseUnit_1161("fakeparent", bus, 1, 0)

    # Pipets
    p300 = protocol.load_instrument('p300_multi_gen2', 'left')
    p20 = protocol.load_instrument('p20_multi_gen2', 'right')

    # Tips
    tiprack_300 = protocol.load_labware('opentrons_96_tiprack_300ul', 9)
    tiprack_20_plate1 = protocol.load_labware('opentrons_96_tiprack_20ul', 10)
    tiprack_20_plate2 = protocol.load_labware('opentrons_96_tiprack_20ul', 11)

    # Plates
    mother_plate1 = protocol.load_labware('greiner_96_petit_puit', 7)
    mother_plate2 = protocol.load_labware('greiner_96_petit_puit', 8)
    plate_to_normalize1 = protocol.load_labware('axygenpcr_96_wellplate_200ul_onspacer', 4)
    plate_to_normalize2 = protocol.load_labware('axygenpcr_96_wellplate_200ul_onspacer', 5)
    op2_plate1 = protocol.load_labware('axygenpcr_96_wellplate_200ul', 1)
    op2_plate2 = protocol.load_labware('axygenpcr_96_wellplate_200ul', 2)

    # Reservoirs
    LadderReservoir = protocol.load_labware('ladder_4_reservoir_63000ul', 6)

    p300.pick_up_tip(tiprack_300.wells()[0])
    p300.aspirate(300, LadderReservoir.wells()[0], 1.5)
    protocol.delay(seconds=0.5, minutes=0)
    p300.dispense(26, op2_plate1.wells()[0].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[8].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[16].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[24].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[32].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[40].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[48].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[56].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[64].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[72].top(-14), 10.0)
    p300.dispense(26, op2_plate1.wells()[80].top(-14), 10.0)
    p300.blow_out(LadderReservoir.wells()[0].top(-5))
    p300.aspirate(40, LadderReservoir.wells()[0], 1.5)
    protocol.delay(seconds=0.5, minutes=0)
    p300.dispense(26, op2_plate1.wells()[88].top(-14), 10.0)
    p300.blow_out(LadderReservoir.wells()[0].top(-5))
    p300.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[0])
    p20.aspirate(10, mother_plate1.wells()[0].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[0].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[0].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(33)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[1].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(32)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[2].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(22)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[3].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(62)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[4].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(35)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[5].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(23)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[6].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(63)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[0].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[0].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[0].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[0].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[8])
    p20.aspirate(10, mother_plate1.wells()[8].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[8].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[8].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(84)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[9].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(46)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[10].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(74)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[11].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(78)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[12].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(87)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[13].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(69)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[14].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(78)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[15].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(83)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[8].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[8].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[8].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[8].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[16])
    p20.aspirate(10, mother_plate1.wells()[16].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[16].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[16].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(17)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[17].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(16)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[18].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(18)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[19].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(8)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[20].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(9)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[21].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(16)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[22].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(26)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[23].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(6)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[16].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[16].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[16].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[16].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[24])
    p20.aspirate(10, mother_plate1.wells()[24].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[24].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[24].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(27)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[25].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(24)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[26].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(27)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[27].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(37)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[28].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(34)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[29].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(30)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[31].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(43)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[24].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[24].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[24].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[24].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[32])
    p20.aspirate(10, mother_plate1.wells()[32].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[32].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[32].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(71)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[33].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(32)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[34].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(63)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[35].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(20)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[36].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(92)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[37].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(47)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[38].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(60)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[32].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[32].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[32].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[32].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[40])
    p20.aspirate(10, mother_plate1.wells()[40].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[40].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[40].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(48)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[41].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(94)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[42].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(67)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[43].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(68)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[44].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(93)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[45].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(56)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[46].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(142)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[47].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(96)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[40].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[40].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[40].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[40].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[48])
    p20.aspirate(10, mother_plate1.wells()[48].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[48].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[48].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(15)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[49].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(23)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[50].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(15)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[51].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(15)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[52].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(14)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[48].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[48].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[48].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[48].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[56])
    p20.aspirate(10, mother_plate1.wells()[56].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[56].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[56].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(7)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[57].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(27)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[58].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(25)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[59].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(38)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[60].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(25)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[61].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(23)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[62].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(38)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[63].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(82)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[56].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[56].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[56].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[56].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[64])
    p20.aspirate(10, mother_plate1.wells()[64].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[64].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[64].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(58)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[65].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(66)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[66].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(82)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[67].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(26)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[68].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(124)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[70].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(29)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[71].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(37)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[64].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[64].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[64].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[64].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[72])
    p20.aspirate(10, mother_plate1.wells()[72].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[72].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[72].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(82)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[73].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(81)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[74].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(79)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[75].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(76)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[76].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(62)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[77].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(100)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[78].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(75)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[79].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(74)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[72].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[72].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[72].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[72].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[80])
    p20.aspirate(10, mother_plate1.wells()[80].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[80].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[80].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(31)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[81].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(31)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[82].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(25)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[83].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(14)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[84].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(18)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[85].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(30)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[86].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(11)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[80].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[80].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[80].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[80].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate1.wells()[88])
    p20.aspirate(10, mother_plate1.wells()[88].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize1.wells()[88].bottom(0), 1)
    p300.move_to(plate_to_normalize1.wells()[88].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(41)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[89].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(35)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[90].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(26)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[91].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(27)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[92].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(26)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[93].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(38)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[94].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(35)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize1.wells()[95].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(78)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize1.wells()[88].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize1.wells()[88].bottom(0), 1)
    p20.dispense(4, op2_plate1.wells()[88].bottom(0), 1)
    p20.mix(3, 15, op2_plate1.wells()[88].bottom(0), 3)
    p20.return_tip()
    p300.pick_up_tip(tiprack_300.wells()[0])
    p300.aspirate(300, LadderReservoir.wells()[0], 1.5)
    protocol.delay(seconds=0.5, minutes=0)
    p300.dispense(26, op2_plate2.wells()[0].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[8].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[16].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[24].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[32].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[40].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[48].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[56].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[64].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[72].top(-14), 10.0)
    p300.dispense(26, op2_plate2.wells()[80].top(-14), 10.0)
    p300.blow_out(LadderReservoir.wells()[0].top(-5))
    p300.aspirate(40, LadderReservoir.wells()[0], 1.5)
    protocol.delay(seconds=0.5, minutes=0)
    p300.dispense(26, op2_plate2.wells()[88].top(-14), 10.0)
    p300.blow_out(LadderReservoir.wells()[0].top(-5))
    p300.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[0])
    p20.aspirate(10, mother_plate2.wells()[0].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[0].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[0].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(88)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[1].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(83)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[2].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(71)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[3].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(58)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[4].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(60)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[5].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(77)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[6].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(80)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[7].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(92)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[0].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[0].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[0].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[0].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[8])
    p20.aspirate(10, mother_plate2.wells()[8].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[8].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[8].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(62)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[9].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(73)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[10].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(74)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[11].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(72)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[12].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(67)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[13].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(64)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[14].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(74)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[15].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(63)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[8].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[8].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[8].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[8].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[16])
    p20.aspirate(10, mother_plate2.wells()[16].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[16].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[16].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(64)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[17].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(70)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[18].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(56)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[19].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(59)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[20].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(51)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[21].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(73)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[22].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(65)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[23].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(77)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[16].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[16].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[16].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[16].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[24])
    p20.aspirate(10, mother_plate2.wells()[24].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[24].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[24].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(65)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[25].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(73)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[26].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(62)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[27].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(63)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[28].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(45)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[29].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(65)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[30].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(66)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[31].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(69)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[24].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[24].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[24].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[24].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[32])
    p20.aspirate(10, mother_plate2.wells()[32].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[32].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[32].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(70)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[33].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(61)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[34].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(60)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[35].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(54)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[36].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(73)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[37].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(77)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[38].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(73)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[39].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(79)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[32].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[32].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[32].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[32].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[40])
    p20.aspirate(10, mother_plate2.wells()[40].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[40].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[40].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(67)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[41].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(68)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[42].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(69)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[43].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(67)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[44].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(68)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[45].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(195)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[46].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(71)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[47].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(57)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[40].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[40].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[40].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[40].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[48])
    p20.aspirate(10, mother_plate2.wells()[48].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[48].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[48].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(67)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[49].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(70)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[50].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(58)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[51].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(49)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[52].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(57)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[53].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(55)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[54].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(72)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[55].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(46)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[48].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[48].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[48].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[48].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[56])
    p20.aspirate(10, mother_plate2.wells()[56].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[56].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[56].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(71)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[57].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(75)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[58].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(58)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[59].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(67)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[60].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(81)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[61].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(76)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[62].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(73)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[63].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(65)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[56].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[56].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[56].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[56].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[64])
    p20.aspirate(10, mother_plate2.wells()[64].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[64].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[64].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(69)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[65].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(62)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[66].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(74)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[67].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(60)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[68].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(74)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[69].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(66)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[70].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(60)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[71].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(91)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[64].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[64].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[64].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[64].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[72])
    p20.aspirate(10, mother_plate2.wells()[72].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[72].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[72].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(74)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[73].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(79)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[74].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(74)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[75].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(69)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[76].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(83)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[77].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(73)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[78].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(67)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[79].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(61)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[72].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[72].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[72].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[72].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[80])
    p20.aspirate(10, mother_plate2.wells()[80].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[80].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[80].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(72)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[81].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(97)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[82].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(78)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[83].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(74)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[84].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(55)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[85].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(80)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[86].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(64)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[87].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(77)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[80].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[80].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[80].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[80].bottom(0), 3)
    p20.return_tip()
    p20.pick_up_tip(tiprack_20_plate2.wells()[88])
    p20.aspirate(10, mother_plate2.wells()[88].bottom(1.3), 1)
    p20.dispense(10, plate_to_normalize2.wells()[88].bottom(0), 1)
    p300.move_to(plate_to_normalize2.wells()[88].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(87)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[89].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(90)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[90].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(87)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[91].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(97)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[92].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(80)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[93].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(84)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[94].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(68)
        pump_1.wait_for_canmove()
    p300.move_to(plate_to_normalize2.wells()[95].center().move(types.Point(x=-2.5,y=84,z=8)))
    if protocol.is_simulating()==False:
        pump_1.wait_for_idle()
        pump_1.dispense(60)
        pump_1.wait_for_canmove()
    p20.mix(3, 15, plate_to_normalize2.wells()[88].bottom(0), 3)
    p20.aspirate(4, plate_to_normalize2.wells()[88].bottom(0), 1)
    p20.dispense(4, op2_plate2.wells()[88].bottom(0), 1)
    p20.mix(3, 15, op2_plate2.wells()[88].bottom(0), 3)
    p20.return_tip()
